Update tensorflow_module.py with "extra" parameter (#12)
* Update tensorflow_module.py with "extra" parameter

To work on Windows, needs the "extra" field in the argument list

* extra in argument is required for sdk

* new deploy flow

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -1,22 +1,42 @@
-# see https://github.com/viamrobotics/build-action for help
 on:
-  push:
-    tags:
-    - '[0-9]+.[0-9]+.[0-9]+'
-    - '[0-9]+.[0-9]+.[0-9]+-rc'
-    - '[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'
-    
+  release:
+    types: [published]
+
+# This regex matches either a semver (e.g. 1.2.3)
+# or a release candidate in one of these forms:
+# 1.2.3-rc or 1.2.3-rc1
+# Adjust the regex below as needed.
+# The pattern:
+#   ^[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]*)?$ 
+# matches to
+#    [0-9]+.[0-9]+.[0-9]+
+# or [0-9]+.[0-9]+.[0-9]+-rc optionally followed by digits
 
 jobs:
-  publish:
+  validate-tag:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v3
-    - uses: viamrobotics/build-action@v1
-      with:
-        # note: you can replace this line with 'version: ""' if you want to test the build process without deploying
-        version: ${{ github.ref_name }}
-        ref: ${{ github.sha }}
-        key-id: ${{ secrets.viam_key_id }}
-        key-value: ${{ secrets.viam_key_value }}
-
+      - name: Validate tag format
+        run: |
+          TAG="${{ github.event.release.tag_name }}"
+          echo "Validating tag: $TAG"
+          if [[ $TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]*)?$ ]]; then
+            echo "Tag matches semver."
+          else
+            echo "Error: tag does not match semvar"
+            exit 1
+          fi
+  publish:
+    needs: validate-tag
+    name: Build and Upload module 
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Build and Publish
+        uses: viamrobotics/build-action@v1.4
+        with:
+          version: ${{ github.event.release.tag_name }}
+          ref: ${{ github.sha }}
+          key-id: ${{ secrets.viam_key_id }}
+          key-value: ${{ secrets.viam_key_value }} 
