re-enable release version validation

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -19,15 +19,14 @@ jobs:
     steps:
       - name: Validate tag format
         run: |
-          echo "remember to undo this when you're ready"
-          #TAG="${{ github.event.release.tag_name }}"
-          #echo "Validating tag: $TAG"
-          #if [[ $TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]*)?$ ]]; then
-          #  echo "Tag matches semver."
-          #else
-          #  echo "Error: tag does not match semvar"
-          #  exit 1
-          #fi
+          TAG="${{ github.event.release.tag_name }}"
+          echo "Validating tag: $TAG"
+          if [[ $TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]*)?$ ]]; then
+            echo "Tag matches semver."
+          else
+            echo "Error: tag does not match semvar"
+            exit 1
+          fi
 
   publish:
     needs: validate-tag
@@ -70,5 +69,3 @@ jobs:
         run: |
           ./viam.exe login api-key --key-id ${{ secrets.viam_key_id }} --key ${{ secrets.viam_key_value }}
           ./viam.exe module upload --platform windows/amd64 --version ${{ github.ref_name }} --upload dist/module.tar.gz
-      - name: REVERTME pip freeze
-        run: pip freeze
